#!/bin/sh
# Plumise Petals Node - One-liner Install Script
# Usage: curl -fsSL https://raw.githubusercontent.com/mikusnuz/plumise-petals/main/scripts/install.sh | sh -s -- --wallet 0xADDRESS
set -e

INSTALL_DIR="$HOME/.plumise-node"
COMPOSE_URL="https://raw.githubusercontent.com/mikusnuz/plumise-petals/main/docker-compose.yml"
IMAGE_CPU="ghcr.io/mikusnuz/plumise-petals:latest"
IMAGE_GPU="ghcr.io/mikusnuz/plumise-petals:gpu"

# -------------------------------------------------------------------
# Helpers
# -------------------------------------------------------------------
info()  { printf "\033[1;34m[INFO]\033[0m  %s\n" "$1"; }
warn()  { printf "\033[1;33m[WARN]\033[0m  %s\n" "$1"; }
error() { printf "\033[1;31m[ERROR]\033[0m %s\n" "$1"; exit 1; }
ok()    { printf "\033[1;32m[OK]\033[0m    %s\n" "$1"; }

# -------------------------------------------------------------------
# Parse arguments
# -------------------------------------------------------------------
WALLET=""
while [ $# -gt 0 ]; do
  case "$1" in
    --wallet)  WALLET="$2"; shift 2 ;;
    --wallet=*) WALLET="${1#*=}"; shift ;;
    *) warn "Unknown option: $1"; shift ;;
  esac
done

# -------------------------------------------------------------------
# OS detection
# -------------------------------------------------------------------
detect_os() {
  OS="$(uname -s)"
  case "$OS" in
    Linux)
      if grep -qi microsoft /proc/version 2>/dev/null; then
        info "Detected OS: Linux (WSL)"
      else
        info "Detected OS: Linux"
      fi
      ;;
    Darwin)
      info "Detected OS: macOS"
      ;;
    *)
      error "Unsupported OS: $OS"
      ;;
  esac
}

# -------------------------------------------------------------------
# Docker check
# -------------------------------------------------------------------
check_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    error "Docker is not installed. Please install Docker first: https://docs.docker.com/get-docker/"
  fi

  if ! docker info >/dev/null 2>&1; then
    error "Docker daemon is not running. Please start Docker and try again."
  fi

  ok "Docker is available"

  if ! command -v docker compose >/dev/null 2>&1 && ! docker compose version >/dev/null 2>&1; then
    error "Docker Compose is not available. Please install Docker Compose: https://docs.docker.com/compose/install/"
  fi

  ok "Docker Compose is available"
}

# -------------------------------------------------------------------
# GPU detection
# -------------------------------------------------------------------
HAS_GPU=false

detect_gpu() {
  if command -v nvidia-smi >/dev/null 2>&1; then
    if nvidia-smi >/dev/null 2>&1; then
      HAS_GPU=true
      GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1)
      ok "NVIDIA GPU detected: $GPU_NAME"
    else
      warn "nvidia-smi found but GPU is not accessible"
    fi
  else
    info "No NVIDIA GPU detected - will use CPU mode"
  fi
}

# -------------------------------------------------------------------
# Install
# -------------------------------------------------------------------
install_node() {
  info "Installing Plumise Petals Node to $INSTALL_DIR"
  mkdir -p "$INSTALL_DIR"
  mkdir -p "$INSTALL_DIR/model-cache"
  mkdir -p "$INSTALL_DIR/data"

  # Download docker-compose.yml
  info "Downloading docker-compose.yml..."
  curl -fsSL "$COMPOSE_URL" -o "$INSTALL_DIR/docker-compose.yml"
  ok "docker-compose.yml downloaded"

  # Create .env file
  cat > "$INSTALL_DIR/.env" <<EOF
# Plumise Petals Node Configuration
# Generated by install.sh

# [REQUIRED] Your agent wallet private key (hex, with 0x prefix)
# You MUST fill this in before starting the node
PLUMISE_PRIVATE_KEY=

# Plumise Chain RPC
PLUMISE_RPC_URL=https://node-1.plumise.com/rpc
PLUMISE_CHAIN_ID=41956

# Oracle
ORACLE_API_URL=https://oracle.plumise.com

# Model to serve (default: bloom-560m)
MODEL_NAME=bigscience/bloom-560m
NUM_BLOCKS=2

# Device (auto/cpu/cuda)
DEVICE=auto

# Wallet address (reference only)
# WALLET=$WALLET
EOF

  ok ".env file created"

  if [ -n "$WALLET" ]; then
    info "Wallet address for reference: $WALLET"
  fi
}

# -------------------------------------------------------------------
# Start node
# -------------------------------------------------------------------
start_node() {
  cd "$INSTALL_DIR"

  if [ "$HAS_GPU" = true ]; then
    info "Starting node with GPU support..."
    docker compose --profile gpu pull
    docker compose --profile gpu up -d
    ok "GPU node started (image: $IMAGE_GPU)"
  else
    info "Starting node in CPU mode..."
    docker compose pull
    docker compose up -d
    ok "CPU node started (image: $IMAGE_CPU)"
  fi
}

# -------------------------------------------------------------------
# Main
# -------------------------------------------------------------------
main() {
  printf "\n"
  printf "\033[1;36m"
  printf "  ____  _                 _            \n"
  printf " |  _ \\| |_   _ _ __ ___ (_)___  ___  \n"
  printf " | |_) | | | | | '_ \` _ \\| / __|/ _ \\ \n"
  printf " |  __/| | |_| | | | | | | \\__ \\  __/ \n"
  printf " |_|   |_|\\__,_|_| |_| |_|_|___/\\___| \n"
  printf "                                        \n"
  printf "  Petals Node Installer\n"
  printf "\033[0m\n"

  detect_os
  check_docker
  detect_gpu
  install_node
  start_node

  printf "\n"
  printf "\033[1;32m========================================\033[0m\n"
  printf "\033[1;32m  Plumise Petals Node Installed!\033[0m\n"
  printf "\033[1;32m========================================\033[0m\n"
  printf "\n"
  printf "  Install directory: %s\n" "$INSTALL_DIR"
  if [ "$HAS_GPU" = true ]; then
    printf "  Mode: \033[1;33mGPU (CUDA)\033[0m\n"
  else
    printf "  Mode: \033[1;34mCPU\033[0m\n"
  fi
  printf "\n"
  printf "\033[1;33m  IMPORTANT: You must set your private key before the node can operate:\033[0m\n"
  printf "  1. Edit %s/.env\n" "$INSTALL_DIR"
  printf "  2. Set PLUMISE_PRIVATE_KEY=0x...\n"
  printf "  3. Restart: cd %s && docker compose restart\n" "$INSTALL_DIR"
  printf "\n"
  printf "  Useful commands:\n"
  printf "    View logs:   cd %s && docker compose logs -f\n" "$INSTALL_DIR"
  printf "    Stop node:   cd %s && docker compose down\n" "$INSTALL_DIR"
  printf "    Restart:     cd %s && docker compose restart\n" "$INSTALL_DIR"
  printf "\n"
}

main
